language: python
python: 3.6
os: linux

stages:
  - run tests
  - name: build packages
    if: branch = master OR branch =~ ^release\/.+
  - name: deploy to artifactory
    if: branch = master OR branch =~ ^release\/.+

env:
  global:
  - ARTIFACTORY_REPO_LINK=https://na.artifactory.swg-devops.com/artifactory/sec-resilient-team-integrations-generic-local
  - TEST_RESILIENT_APPLIANCE=staging2.internal.resilientsystems.com
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"
  - PIP_FIND_LINKS="$TRAVIS_BUILD_DIR/pkgs"
  - LATEST_TAG=$(git describe --abbrev=0 --tags)
  - LIB_VERSION=$(echo $LATEST_TAG | cut -d "." -f 1,2)
  - NEW_VERSION=$LIB_VERSION.$TRAVIS_BUILD_NUMBER
  - BASE_ARTIFACTORY_PATH=resilient-python-api/$LIB_VERSION/$NEW_VERSION
  - RUN_INT_TESTS_KEYWORD="[run-int-tests]"
  - RUN_INT_TESTS=$([[ "$TRAVIS_COMMIT_MESSAGE" != *"$RUN_INT_TESTS_KEYWORD"* ]]; echo $?)
  - FYRE_CLUSTER_NAME="${TRAVIS_BUILD_NUMBER}hydratest"
  - FYRE_CLUSTER_DOMAIN="${FYRE_CLUSTER_NAME}1.fyre.ibm.com"
  - FYRE_STENCIL_ID="6609"
  - FYRE_DEPLOY_SLEEP_SECONDS=30
  - FYRE_DEPLOY_TIMEOUT_SECONDS=180
  - PATH_MOCK_APP_CONFIG="$TRAVIS_BUILD_DIR/travis-scripts/mock_app_config"

# Install package deps
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools

matrix:
  fast_finish: true

  include:
    - stage: run tests
      name: Python 2.7 Unit Tests
      python: 2.7
      env: RUN_TYPE=unit_test TOXENV=py27 TEST_RESILIENT_ORG="Resilient PS - Test"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 2.7 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: run tests
      name: Python 3.6 Unit Tests
      python: 3.6
      env: RUN_TYPE=unit_test TOXENV=py36 TEST_RESILIENT_ORG="Resilient PS - Test2"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 3.6 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: run tests
      name: Python 3.6 Integration Tests
      python: 3.6
      env: RUN_TYPE=int_test TOXENV=py36
      install: ./travis-scripts/install_int_tests_deps.sh
      script:
        - if [ $RUN_INT_TESTS == 1 ]; then
            ./travis-scripts/manage_fyre_instance.sh DEPLOY;
            ./travis-scripts/run_int_tests.sh;
          fi
      after_script:
        - if [ $RUN_INT_TESTS == 1 ]; then
            ./travis-scripts/manage_fyre_instance.sh DELETE $FYRE_CLUSTER_NAME;
          fi

    - stage: build packages
      name: Build Packages in Python 2.7
      python: 2.7
      script:
        - echo "Building packages in Python 2.7"
        - ./travis-scripts/build_and_deploy_packages.sh no_deploy
      
    - stage: build packages
      name: Build Packages in Python 3.6
      python: 3.6
      script:
        - echo "Building packages in Python 3.6"
        - ./travis-scripts/build_and_deploy_packages.sh no_deploy

    - stage: deploy to artifactory
      script:
        - echo "Building packages in Python 3.6 and Deploying to Artifactory"
        - ./travis-scripts/build_and_deploy_packages.sh do_deploy
        - echo "Sending notification to Slack"
        - ./travis-scripts/send_slack_notification.sh "Link to Artifactory - <$ARTIFACTORY_REPO_LINK/$BASE_ARTIFACTORY_PATH|$NEW_VERSION>" "success"

after_failure:
  - ./travis-scripts/send_slack_notification.sh "resilient-python-api failed to build" "failure"