language: python
python: 3.6
os: linux

stages:
  - run tests
  - name: deploy to artifactory
    # if: branch = master OR branch =~ ^release\/.+

env:
  global:
  - ARTIFACTORY_REPO_LINK=https://na.artifactory.swg-devops.com/artifactory/sec-resilient-team-integrations-generic-local
  - TEST_RESILIENT_APPLIANCE=staging2.internal.resilientsystems.com
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"
  - PIP_FIND_LINKS="$TRAVIS_BUILD_DIR/pkgs"
  - LATEST_TAG=$(git tag --list | tail -n 1)
  - LIB_VERSION=$(echo $LATEST_TAG | cut -d "." -f 1,2)
  - NEW_VERSION=$LIB_VERSION.$TRAVIS_BUILD_NUMBER
  - BASE_ARTIFACTORY_PATH=resilient-python-api/$LIB_VERSION/$NEW_VERSION

# Install package deps
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools

matrix:
  fast_finish: true

  include:
    - stage: run tests
      name: Python 2.7 Tests
      python: 2.7
      env: TOXENV=py27 TEST_RESILIENT_ORG="Resilient PS - Test"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 2.7 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: run tests
      name: Python 3.6 Tests
      python: 3.6
      env: TOXENV=py36 TEST_RESILIENT_ORG="Resilient PS - Test2"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 3.6 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: deploy to artifactory
      script:
        - echo "Deploying to Artifactory"
        - ./travis-scripts/deploy_artifactory.sh
