language: python
python: 3.6
os: linux

stages:
  - run tests
  - name: build packages
    if: branch = master OR branch =~ ^release\/.+
  - name: deploy to artifactory
    if: branch = master OR branch =~ ^release\/.+
  - name: deploy documentation
    if: branch = master
  - name: release to pypi
    if: tag =~ ^release\/pypi\/.+

env:
  global:
  - ARTIFACTORY_REPO_LINK=https://na.artifactory.swg-devops.com/artifactory/sec-resilient-team-integrations-generic-local
  - TEST_RESILIENT_APPLIANCE=staging2.internal.resilientsystems.com
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"
  - PIP_FIND_LINKS="$TRAVIS_BUILD_DIR/pkgs"
  - LATEST_TAG=$(git describe --abbrev=0 --tags)
  - IS_MASTER=$([[ "$TRAVIS_BRANCH" != *"master"* ]]; echo $?)
  - IS_RELEASE=$([[ "$TRAVIS_BRANCH" != *"release/"* ]]; echo $?)
  - LIB_VERSION=`if [[ $IS_RELEASE -eq 1 ]]; then echo $(echo ${TRAVIS_BRANCH##*/} | cut -d "." -f 1,2); else echo $(echo $LATEST_TAG | cut -d "." -f 1,2); fi`
  - NEW_VERSION=$LIB_VERSION.$TRAVIS_BUILD_NUMBER
  - SETUPTOOLS_SCM_PRETEND_VERSION=$NEW_VERSION
  - BASE_ARTIFACTORY_PATH=resilient-python-api/$LIB_VERSION/$NEW_VERSION
  - PATH_TEMPLATE_PYPIRC="$TRAVIS_BUILD_DIR/travis-scripts/template.pypirc"

# Install package deps
before_install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools

matrix:
  fast_finish: true

  include:
    - stage: run tests
      name: Python 2.7 Tests
      python: 2.7
      env: TOXENV=py27 TEST_RESILIENT_ORG="Resilient PS - Test"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 2.7 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: run tests
      name: Python 3.6 Tests
      python: 3.6
      env: TOXENV=py36 TEST_RESILIENT_ORG="Resilient PS - Test2"
      install: ./travis-scripts/install_unit_tests_deps.sh
      script:
        - echo "Starting Python 3.6 Tests"
        - ./travis-scripts/run_unit_tests.sh

    - stage: build packages
      name: Build Packages in Python 2.7
      python: 2.7
      script:
        - echo "Building packages in Python 2.7"
        - ./travis-scripts/build_and_deploy_packages.sh no_deploy
      
    - stage: build packages
      name: Build Packages in Python 3.6
      python: 3.6
      script:
        - echo "Building packages in Python 3.6"
        - ./travis-scripts/build_and_deploy_packages.sh no_deploy

    - stage: deploy to artifactory
      script:
        - echo "Building packages in Python 3.6 and Deploying to Artifactory"
        - ./travis-scripts/build_and_deploy_packages.sh do_deploy
        - echo "Sending notification to Slack"
        - ./travis-scripts/send_slack_notification.sh "Link to Artifactory - <$ARTIFACTORY_REPO_LINK/$BASE_ARTIFACTORY_PATH|$NEW_VERSION> \n Install command - \`\`\`pip install -U <package-name> -i https://<EMAIL_ADDRESS>:<ARTIFACTORY_API_KEY>@na.artifactory.swg-devops.com/artifactory/api/pypi/sec-resilient-team-integrations-pypi-virtual/simple\`\`\` " "success"

    - stage: release to pypi
      install:
        - pip install twine
      script:
        - echo "Building packages in Python 3.6 and releasing to PyPi"
        - ./travis-scripts/build_and_deploy_packages.sh no_deploy do_release
        - echo "Sending notification to Slack"
        - ./travis-scripts/send_slack_notification.sh "Succesfully released $NEW_VERSION to PyPi" "success"

    - stage: deploy documentation
      # Install sphinx to handle the rebuild and deploy of docs, install the packages so that their code and comments can be gathered
      install:
      - pip install sphinx resilient resilient-circuits resilient-lib resilient-sdk pytest-resilient-circuits rc-cts rc-webserver
      script:
        - make -C docs/ html
        - touch docs/_build/html/.nojekyll
      # Define a deploy step to the inbuilt git pages deployment provider
      deploy:
        - provider: pages:git
          verbose: true
          skip_cleanup: true
          # The github_url for the internal git needs to be specified otherwise the deploy will fail.
          github_url: github.ibm.com
          # A token is needed for the deployment, this token is a Personal Access token with limited permissions
          github_token: $GH_TOKEN
          edge: true
          local_dir: ./docs/_build/html/
          keep_history: true

after_failure:
  - ./travis-scripts/send_slack_notification.sh "resilient-python-api failed to build" "failure"